# -*- coding: utf-8 -*-
"""Predictive_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp2aO1iq_GGsVXKWVi3u_pOB0qcznRBj

# Proyek Predictive Analytics - Prediksi Tingkat Nilai Siswa

- **Nama:** Nur Adilah
- **Email:** nuradilah@students.usu.ac.id
- **ID Dicoding:** MC319D5X0793 NUR ADILAH

###Pendahuluan

Setiap institusi pendidikan memiliki tantangan dalam memastikan siswa mampu menyelesaikan pendidikannya dengan baik. Namun, tidak semua siswa memiliki latar belakang dan kebiasaan belajar yang mendukung keberhasilan akademik mereka.

Melalui proyek ini, kita ingin memprediksi memprediksi tingkat atau kategori nilai akhir siswa (GradeClass 0-4). Menggunakan berbagai faktor seperti usia, jenis kelamin, waktu belajar mingguan, absensi, dan dukungan orang tua. Dengan memanfaatkan algoritma machine learning, sekolah atau guru dapat mendeteksi siswa yang berisiko tidak lulus lebih awal dan mengambil langkah preventif.

Model prediksi kelulusan ini dapat membantu:
- Guru memberikan perhatian dan bimbingan yang lebih sesuai kepada siswa berdasarkan potensi tingkat nilai mereka.
- Sekolah merancang program intervensi, dukungan, atau pengayaan yang ditargetkan untuk kelompok siswa dengan tingkat nilai tertentu.
- Orang tua lebih memahami posisi akademik anak dan memberikan dukungan yang diperlukan.

### Tujuan

- Membangun model membangun model klasifikasi multi-kelas yang akurat untuk memprediksi GradeClass siswa, memungkinkan deteksi dini potensi performa akademik di berbagai tingkatan.

# Data Understanding

Dataset yang digunakan dalam proyek ini adalah `Student_performance.csv` yang berisi data performa akademik siswa. Tujuan dari tahap ini adalah untuk memahami struktur dataset, mengetahui jenis data, dan melihat distribusi data secara umum.

**Data Loading**

Melakukan load dataset, kemudian import library pandas untuk dapat membaca file datanya. Dataset yang akan kita gunakan bernama Student_performance.csv ingkat nilai akhir siswa (multi-kelas) menggunakan GradeClass. Dataset ini berasal dari kaggle "Students Performance Dataset"
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# load dataset
student = pd.read_csv('/content/Student_performance.csv')
student

"""- ada 2.392 baris dalam dataset.
- Terdapat 15 kolom yaitu: StudentID, Age, Gender (0 = perempuan dan 1 = laki-laki), Ethnicity, ParentalEducation (Tingkat pendidikan orang tua), StudyTimeWeekly (Waktu belajar mingguan siswa (dalam jam)), Absences (Jumlah ketidakhadiran), Tutoring (Mengikuti les tambahan (0 = tidak, 1 = ya)), ParentalSupport (Dukungan orang tua (0 = tidak, 1 = ya)), Extracurricular,	Sports,	Music,	Volunteering,	GPA (Nilai rata-rata akademik siswa),	GradeClass (Kategori nilai akhir (0–4)).

# Exploratory Data Analysis - Deskripsi Variabel
"""

# cek informasi pada dataset
student.info()

"""Dari output terlihat bahwa:

- Terdapat 3 kolom dengan tipe data float64 yaitu: StudyTimeWeekly, GPA, dan GradeClass. Namun baiknya kolom GradeClass dibuah menjaid tipe data integer karena pada kolom tersebut isinya menunjukkan kelas diskrit (seperti 1.0, 2.0, dst), sehingga lebih tepat jika dikonversi ke tipe int.
- Terdapat 12 kolom dengan tipe data int64 yaitu: StudentID, Age, Gender, Ethnicity,	ParentalEducation, Absences,	Tutoring,	ParentalSupport,	Extracurricular,	Sports,	Music,	Volunteering.

Nah, setelah diperhatikan, terdapat beberapa kolom yang sebaiknya diubah ke tipe data kategori (category) seperti mengubah kolom GradeClass ke integer, kemudian mengidentifikasi variabel kategorikal (Gender, Ethnicity, ParentalEducation, dll).
"""

student.describe()

"""**Insight:**

- Count: Semua kolom memiliki jumlah data yang sama (2392), menunjukkan tidak ada missing values.
- Mean: Rata-rata usia siswa adalah sekitar 15 - 18 tahun. Rata-rata waktu belajar mingguan sekitar 9.8 jam. Rata-rata absensi sekitar 14 kali. Rata-rata GPA sekitar 2.4.
- Std: Menunjukkan sebaran data. Usia dan GPA memiliki sebaran yang relatif kecil, sedangkan Waktu Belajar dan Absensi memiliki sebaran yang lebih besar.
- Min/Max: Menunjukkan rentang nilai. Usia siswa bervariasi dari 15 hingga 18 tahun. Waktu belajar dari 0 hingga 20 jam. Absensi dari 0 hingga 29 hari. GPA dari 0 hingga 4.
- 25%/50%/75% (Quartiles): Memberikan gambaran distribusi data. Median (50%) GPA sekitar 2.45, menunjukkan setengah siswa memiliki GPA di bawah nilai ini dan setengahnya di atas.
"""

student.isnull().sum()

"""**Insight:**

- Tidak ada missing values sama sekali (0 di semua kolom).

- Artinya, kita tidak perlu mengisi atau menghapus data karena semuanya lengkap.
"""

# Mengubah 'GradeClass' menjadi tipe data integer
student['GradeClass'] = student['GradeClass'].astype(int)
student['GradeClass'].unique()

"""**Insight:**

Dari output tersebut array([2, 1, 4, 3, 0]) menunjukkan bahwa kolom 'GradeClass' hanya memiliki lima nilai unik, yaitu 0, 1, 2, 3, dan 4. Ini mengindikasikan bahwa "kelas nilai akhir" siswa dikategorikan ke dalam lima tingkatan yang berbeda.
"""

# Mengubah tipe data 'GradeClass' ke integer
student['GradeClass'] = student['GradeClass'].astype(int)

# Ubah kolom-kolom kategorikal ke tipe kategori
categorical_features = ['Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering']

# Ubah tipe data jadi category
student[categorical_features] = student[categorical_features].astype('category')

# Cek hasil perubahan
student.dtypes

"""**Insight:**

Berhasil mengubah tipe data pada kolom 'GradeClass' menjadi integer dan beberapa kolom lainnya seperti (Gender. Ethnicity, dll.) menjadi tipe data kategori. Ini mengkonfirmasi bahwa perubahan tipe data berhasil diterapkan, mengoptimalkan penggunaan memori dan performa, serta menyiapkan data dengan tepat untuk analisis dan pemodelan selanjutnya.

## Menangani Outliers
"""

# cek outlier

sns.set(style="whitegrid")

numerical_features = ['Age', 'StudyTimeWeekly', 'Absences', 'GPA']

plt.figure(figsize=(10, 8))
for i, col in enumerate(numerical_features):
  plt.subplot(2, 2, i + 1)
  sns.boxplot(x=student[col], color='skyblue')
  plt.title(f'Boxplot {col}')

plt.tight_layout()
plt.show()

"""**Insight:**

Berikut hasil deteksi outlier berdasarkan boxplot:
- 'Age', tidak terlihat outlier yang signifikan. Distribusinya normal antara usia 15 - 18 tahun.
- 'StudyTimeWeekly', terlihat ada beberapa nilai ekstrem seperti di dekat 0 dan 20 jam, tapi tidak terlalu mencolok.
- 'Absences', walau agak tersebar luas, tidak ada nilai yang muncul sebagai outlier.
- 'GPA', semua data dalam rentang normal (0–4) tanpa titik mencurigakan.

## Univariate Analysis

Memisahkan fitur menjadi Numerical Features dan Categorical Features
"""

# Numerical features
numerical_features = ['Age', 'StudyTimeWeekly', 'Absences', 'GPA']

# Categorical Features
categorical_features = ['Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GradeClass']

"""Fitur sudah dipisah menjadi 2 yaitu numerical_features dan categorical_features.

#### Categorical Features
"""

# Cek distribusi kolom kategorikal
categorical_cols = ['Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering']

plt.figure(figsize=(18, 18))
for i, col in enumerate(categorical_cols):
  plt.subplot(3, 3, i + 1)
  sns.countplot(data=student, hue=col, x=col, palette="pastel")
  plt.title(f'Distribusi {col}')
  plt.xlabel(col)
  plt.ylabel('Count')
  plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""**Insight:**

Dari visualisasi distribusi kolom kategorikal memperolrh informasi:

1. Gender
  - Distribusi antara kode 0 dan 1 relatif seimbang (~50:50).
  - Bisa diasumsikan ini laki-laki vs perempuan (tapi pastikan dulu dari dokumentasi/sumber data).

2. Ethnicity
  - Kode 0 mendominasi jumlah data (~1200), sementara kategori lain (1–3) jauh lebih sedikit.
  - Potensi imbalance, perlu dipertimbangkan saat modeling.

3. ParentalEducation
  - Kategori 2 paling dominan, disusul kategori 1 dan 3.
  -Kategori 4 sangat sedikit → kemungkinan bisa digabung (jika masuk akal secara domain).

4. Tutoring
  - Mayoritas siswa tidak ikut bimbingan belajar (kode 0).
  - Ini bisa jadi fitur penting karena distribusinya tidak seimbang.

5. ParentalSupport
  - Mayoritas di kategori 2 dan 3.
  - Kategori 0 dan 4 jumlahnya cukup sedikit.

6. Extracurricular
  - Siswa yang ikut kegiatan ekstrakurikuler (kode 1) lebih sedikit dibanding yang tidak.
  - Potensi jadi fitur signifikan.

7. Sports
  - Sama seperti extracurricular — lebih banyak siswa yang tidak aktif di olahraga.

8. Music
  - Hanya sebagian kecil siswa yang terlibat di bidang musik (~20%).

9. Volunteering
  - Hanya sedikit siswa yang ikut kegiatan sukarelawan (~20%).

## Numerical features
"""

# cek distribusi kolom numerik
sns.set(style='whitegrid')

# membuat histogram
numerical_cols = ['Age', 'StudyTimeWeekly', 'Absences', 'GPA']

plt.figure(figsize=(16, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(2, 2, i+1)
    sns.histplot(student[col], kde=True, bins=30, color='skyblue')
    plt.title(f'Distribusi {col}')

plt.tight_layout()
plt.show()

"""**Insight:**

Dari output diatas dapat dilihat:

1. Adge
  - Usia siswa berkisar antara 15 - 18 tahun. Hasil dari distribusi relatif merata, artinya jumlah siswa di setiap usia hampir seimbang.

2. StudyTimeWeekly
  - Rata-rata siswa menghabiskan waktu belajar mingguan di kisaran 8–12 jam.
  - Distribusinya cukup merata, sedikit condong ke tengah → tidak terlalu banyak outlier ekstrim.
  - Tidak ada lonjakan signifikan di waktu belajar sangat rendah atau tinggi.

3. Absences
  - Jumlah absensi tersebar cukup merata dari 0 sampai 29.
  - Ada sedikit tren penurunan di ujung kanan → semakin sedikit siswa yang memiliki absensi tinggi.
  - Distribusi ini terlihat sedikit miring ke kanan, artinya sebagian kecil siswa sering bolos.

4. GPA
  - GPA mayoritas siswa berada di rentang 1.0 – 3.0.
  - Distribusinya mendekati normal (bell curve), tapi sedikit condong ke kanan.
  - Sedikit siswa yang memiliki GPA mendekati 0 atau 4.0, menunjukkan nilai sangat rendah atau sangat tinggi jarang.

# Exploratory Data Analysis - Multivariate Analysis

Analisis hubungan fitur kategorikal terhadap GPA
"""

categorical_features = ['Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering']

plt.figure(figsize=(20, 25))
for i, col in enumerate(categorical_features):
  plt.subplot(5, 2, i + 1)
  sns.boxplot(x=student[col], y=student['GPA'])
  plt.title(f'Scatterplot {col} vs GPA')
plt.tight_layout()
plt.show()

"""**Insight:**

Dilihat dari hasil pengamatan dari analisis hubungan fitur kategorikal vs GPA:

- Fitur 'Tutoring' vs 'GPA', Siswa yang ikut tutoring cenderung punya median GPA lebih tinggi.
- Fitur 'ParentalSupport', Semakin tinggi dukungan orang tua (semakin ke kanan), GPA cenderung meningkat.
- Fitur 'Extracurricular', 'Music', 'Volunteering', Perbedaannya tidak terlalu besar, tapi tetap bisa dilihat variasinya.
- Fitur 'Gender' dan 'Ethnicity', Tidak terlihat perbedaan mencolok antara kategori terhadap GPA.
- Fitur 'ParentalEducation', Terlihat ada tren penurunan GPA pada level pendidikan orang tua yang lebih tinggi — bisa jadi faktor lain yang mempengaruhi.
"""

# Cek rata-rata GPA tiap kategori
for col in categorical_features:
  mean_gpa = student.groupby(col)['GPA'].mean()
  print(f"Rata-rata GPA berdasarkan {col}:\n{mean_gpa}\n")

"""**Insight:**

Dilihat dari hasil nilai rata-rata tersebut per variabel (fitur)
- 'Gender' Rata-rata GPA laki-laki (0) sedikit lebih tinggi daripada perempuan (1).
- 'Ethnicity'	Terdapat variasi kecil, tapi Ethnicity 1 dan 3 sedikit unggul di GPA.
- 'ParentalEducation'	Pendidikan orang tua tingkat 1 & 2, GPA anak lebih tinggi. Tingkat 3 & 4, lebih rendah.
- 'Tutoring'	Siswa yang ikut tutoring - GPA lebih tinggi secara signifikan (+0.29).
- 'ParentalSupport'	Dukungan orang tua sangat berkorelasi → Semakin tinggi support - GPA naik.
- 'Extracurricular'	Aktif ekskul - GPA lebih tinggi (+0.18).
- 'Sports'	Siswa yang olahraga - GPA lebih tinggi (+0.11).
- 'Music'	Bermusik - GPA lebih tinggi (+0.17).
- 'Volunteering'	Sedikit perbedaan (volunteer = 1.91 vs tidak = 1.90) - tidak signifikan.

Kesimpulannya, terdapat beberapa faktor yang berkorelasi positif terhadap GPA yaitu 'Tutoring, 'ParentalSupport', 'Extracurricular' activities (termasuk Sports & Music)

**Numerical Features**

Untuk mengamati hubungan antara fitur numerik, kita akan menggunakan fungsi pairplot(). Kita juga akan mengobservasi korelasi antara fitur numerik dengan fitur target menggunakan fungsi corr().
"""

numerical_features = student.select_dtypes(include=['float64', 'int64'])

sns.pairplot(numerical_features, diag_kind='kde')
plt.suptitle('Pairplot untuk Fitur Numerik', y=1.02)
plt.show()

"""**Insight:**

- Absences vs GPA: Terdapat hubungan negatif yang cukup jelas, dimana semakin sering siswa absen, semakin rendah nilai GPA mereka.

- StudyTimeWeekly vs GPA: Ada kecenderungan bahwa semakin banyak waktu belajar mingguan, nilai GPA cenderung meningkat, meskipun hubungan ini tidak terlalu kuat.

- GradeClass dan GPA: Nilai GradeClass cenderung turun seiring meningkatnya GPA, menunjukkan bahwa GPA yang tinggi berhubungan dengan peringkat kelas yang lebih baik.

**Correlation Matrix**
"""

numerical_features = student.select_dtypes(include=['float64', 'int64'])

correlation_matrix = numerical_features.corr()

# Visualisasi plot heatmap korelasi
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Heatmap Korelasi Antar Variabel Numerik')
plt.show()

"""**Insight:**

- GPA memiliki korelasi negatif yang sangat kuat terhadap Absences (-0.92). Artinya, semakin sering siswa absen, semakin rendah nilai GPA mereka.
- GradeClass juga berkorelasi negatif cukup kuat dengan GPA (-0.78). Hal ini masuk akal karena semakin tinggi nilai GPA, maka semakin besar kemungkinan siswa mendapatkan kelas nilai yang tinggi (GradeClass lebih rendah = lebih baik).
- Absences berkorelasi positif dengan GradeClass (0.73). Ini menunjukkan bahwa siswa yang sering absen cenderung mendapatkan kelas nilai yang lebih rendah (GradeClass lebih tinggi).
- Fitur lainnya seperti ParentalSupport, StudyTimeWeekly, dan ParentalEducation hanya menunjukkan korelasi lemah dengan GradeClass, sehingga kemungkinan pengaruhnya tidak terlalu signifikan secara langsung terhadap kelulusan siswa.
- StudentID dan Age tampaknkelihatannya tidak memiliki pengaruh berarti terhadap fitur target (GradeClass) karena nilai korelasinya mendekati nol.

"""

# Hitung korelasi antar fitur numerik
correlation = numerical_features.corr()

# Korelasi dengan GPA saja
correlation_with_gpa = correlation["GPA"].sort_values(ascending=False)

# Tampilkan korelasi GPA
print("Korelasi dengan GPA:\n")
print(correlation_with_gpa)

"""**Insight:**

- Absences (-0.919): Merupakan fitur yang paling berkorelasi negatif dengan GPA. Artinya, semakin sering siswa absen, semakin rendah GPA mereka. Ini adalah faktor risiko utama terhadap penurunan prestasi.

- GradeClass (-0.783): Juga memiliki korelasi negatif yang kuat. Siswa dengan GPA tinggi cenderung memiliki peringkat kelas yang lebih baik.

- StudyTimeWeekly (+0.179): Korelasi positif lemah. Ada indikasi bahwa semakin banyak waktu yang dihabiskan untuk belajar setiap minggu, GPA cenderung meningkat, meskipun tidak terlalu signifikan.

- Age (0.0003) dan StudentID (-0.0027): Tidak memiliki hubungan yang berarti terhadap GPA. Kemungkinan besar hanya bersifat administratif atau identitas siswa.

# Data Preparation

### Encoding Fitur Kategori
"""

from sklearn.preprocessing import OneHotEncoder

# pisahkan target dan fitur
X = student.drop(columns=["GradeClass", "StudentID"])
y = student["GradeClass"]

# 2. One-hot encoding fitur kategorikal pakai get_dummies
categorical_features = ['Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring',
                        'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering']

X = pd.get_dummies(X, columns=categorical_features, drop_first=True)
student.head()

"""**Insight:**

 fitur kategorikal telah berhasil diubah menjadi format numerik menggunakan one-hot encoding.


"""

student.isnull().sum()

"""**Insight:**

Setelah di cek kembali, Tidak ada missing values sama sekali (0 di semua kolom).

### Train-Test-Split
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""**Insight:**

Kode ini membagi dataset menjadi dua bagian: 80% untuk melatih model (X_train, y_train) dan 20% untuk menguji performa model pada data baru (X_test, y_test). Penggunaan random_state=42 memastikan hasil pembagian data konsisten setiap kali kode dijalankan, sehingga proyek Anda menjadi reproduktif.

### Standarisasi
"""

from sklearn.preprocessing import StandardScaler

numerical_features = ['Age', 'StudyTimeWeekly', 'Absences']
scaler = StandardScaler()
X_train[numerical_features] = scaler.fit_transform(X_train[numerical_features])
X_test[numerical_features] = scaler.transform(X_test[numerical_features])
X_train[numerical_features].head()

"""**Insight:**

Setelah distandardisasi menggunakan StandardScaler, nilai fitur numerik ('Age', 'StudyTimeWeekly', 'Absences') tidak lagi dalam satuan aslinya, melainkan direpresentasikan sebagai skor-z (z-scores) yang menunjukkan jarak setiap nilai dari rata-rata dalam satuan standar deviasi. Nilai positif berarti di atas rata-rata, negatif berarti di bawah rata-rata, dan nilai mendekati nol berarti dekat dengan rata-rata.
"""

X_train[numerical_features].describe().round(4)

"""**Insight:**

Fitur-fitur numerik sekarang memiliki rata-rata mendekati nol dan standar deviasi mendekati satu, yang merupakan kondisi ideal untuk banyak algoritma machine learning yang sensitif terhadap skala data.

### Reduksi Dimensi dengan Principal Component Analysis (PCA)
"""

from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print("Jumlah komponen PCA:", X_train_pca.shape[1])

"""**Insight:**

Setelah reduksi dimensi dengan PCA (n_components=0.95):

PCA secara otomatis memilih 15 komponen utama yang bisa menjelaskan 95% total variasi (informasi) dalam data.

# Model Development

Pada tahap ini, kita akan membangun model klasifikasi untuk memprediksi tingkat nilai akhir siswa (GradeClass 0-4). Kita akan mencoba beberapa algoritma dan mengevaluasi performanya.

Kita akan membuat tiga buah model machine learning dangan algoritma berikut:
1. Logistic Regression
2. Random Foreat
3. Gradient Boosting Classifier

###### Logistic Regression
"""

from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

"""###### Random Forest"""

from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

"""###### Gradient Boosting"""

from sklearn.ensemble import GradientBoostingClassifier
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)

y_pred_gb = gb_model.predict(X_test)

"""# Evaluasi"""

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, accuracy_score, precision_score, recall_score, f1_score

print("Logistic Regression:")
print("Accuracy:", round(accuracy_score(y_test, y_pred_lr), 2))
print("Precision (weighted avg):", round(precision_score(y_test, y_pred_lr, average='weighted'), 2))
print("Recall (weighted avg):", round(recall_score(y_test, y_pred_lr, average='weighted'), 2))
print("F1 Score (weighted avg):", round(f1_score(y_test, y_pred_lr, average='weighted'), 2))
print()

print("Random Forest:")
print("Accuracy:", round(accuracy_score(y_test, y_pred_rf), 2))
print("Precision (weighted avg):", round(precision_score(y_test, y_pred_rf, average='weighted'), 2))
print("Recall (weighted avg):", round(recall_score(y_test, y_pred_rf, average='weighted'), 2))
print("F1 Score (weighted avg):", round(f1_score(y_test, y_pred_rf, average='weighted'), 2))
print()

print("Logistic Regression:")
print("Accuracy:", round(accuracy_score(y_test, y_pred_gb), 2))
print("Precision (weighted avg):", round(precision_score(y_test, y_pred_gb, average='weighted'), 2))
print("Recall (weighted avg):", round(recall_score(y_test, y_pred_gb, average='weighted'), 2))
print("F1 Score (weighted avg):", round(f1_score(y_test, y_pred_gb, average='weighted'), 2))
print()

"""Berdasarkan hasil evaluasi dan metrik klasifikasi yang telah dilakukan, model yang paling optimal untuk digunakan dalam prediksi GradeClass adalah model Random Forest Anda (akibat akurasi 91%) secara langsung menjawab tujuan proyek dan berdampak positif pada business understanding.

1. Model membantu mengidentifikasi siswa yang berpotensi berjuang (GradeClass rendah) atau berpotensi sukses (GradeClass tinggi) berdasarkan faktor-faktor dalam data, yang merupakan inti tantangan institusi pendidikan.

2. Model berhasil membangun model klasifikasi multi-kelas yang akurat untuk memprediksi GradeClass, memungkinkan deteksi dini potensi performa akademik siswa

3. Adapun dampak dari setiap solusi steatment yaitu:

- Prediksi model memungkinkan guru fokus membimbing siswa berisiko, mengoptimalkan waktu mereka.
- Prediksi memungkinkan sekolah membuat program dukungan (intervensi/pengayaan) yang sangat spesifik dan tertarget pada kelompok siswa yang memerlukannya.
-  Informasi prediksi membantu orang tua lebih memahami potensi anak dan memberikan dukungan yang tepat di rumah.


"""